Adds tweenBuffer
wethegit/wtc-perspective-card pull request #12
Opened 2020-07-20 18:58 UTC by NicholasLancey

## Description

QA encountered an issue where if you clicked on the clickable card directly after it closed, it would reopen in a broken state. 

## Solution

@liamegan and I added a 1 second buffer to prevent the card from being reopened straight away.

2020-07-21 13:47 UTC, liamegan requested changes

2020-07-21 13:47 UTC, liamegan commented on src/wtc-perspective-card.js
> +      this._tweenBuffer == false
Please change this to `=== false`

2020-07-21 16:05 UTC, marlonmarcello commented on src/wtc-perspective-card.js
> +      this._tweenBuffer = true;
If I read the problem correctly, the issue is clicking on the card as soon as it closes right?
Shouldn't this buffer be turned ON and then after a second be turned OFF when setting `_tweening` to `false` then instead?

2020-07-21 20:19 UTC, liamegan commented
Depending on the implementation - ie if you were to extend it to allow
clicking of the card when enlarged - then this problem would still present
itself. This fix just protects against both potentials.


---------------------------------------------------------------
Liam Egan  |  We The Collective Design Inc.

37 Dunlevy Ave.
Vancouver BC V6A 3A3

Phone: +1 (604) 363-6466

www.wethecollective.com


On Tue, Jul 21, 2020 at 9:05 AM Marlon Ugocioni Marcello <
notifications@github.com> wrote:

> *@marlonmarcello* commented on this pull request.
> ------------------------------
>
> In src/wtc-perspective-card.js
> <https://github.com/wethegit/wtc-perspective-card/pull/12#discussion_r458213894>
> :
>
> > @@ -981,6 +986,12 @@ class ClickablePerspectiveCard extends PerspectiveCard {
>     * @default false
>     */
>    set tweening(value) {
> +    if (value !== this._tweening) {
> +      this._tweenBuffer = true;
>
> If I read the problem correctly, the issue is clicking on the card as soon
> as it closes right?
> Shouldn't this buffer be turned ON and then after a second be turned OFF
> when setting _tweening to false then instead?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wethegit/wtc-perspective-card/pull/12#pullrequestreview-452609630>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEZJ2GQOICEKJTV2YWBZYDR4W4EFANCNFSM4PCVTC4A>
> .
>

2020-07-21 22:12 UTC, marlonmarcello commented
Got it!

2020-07-21 22:12 UTC, marlonmarcello commented on src/wtc-perspective-card.js
> +      this._tweenBuffer == false
Will merge after this one.

2020-07-31 23:40 UTC, NicholasLancey commented
All good to go @marlonmarcello

2020-08-04 15:52 UTC, marlonmarcello commented
Thank you guys!

2020-08-04 15:52 UTC, marlonmarcello approved these changes

2020-08-04 15:52 UTC, merged