Adds nvmrc and update dependabot.yml
wethegit/wtc-perspective-card pull request #69
Opened 2024-07-31 21:43 UTC by marlonmarcello

# Description

Fixes issues with package version and build conflicts.

2024-08-06 20:53 UTC, wonderfulfrog submitted a review, later dismissed

2024-08-06 21:15 UTC, wonderfulfrog requested changes
I couldn't install this without using a recent version of Python 3 (in my case 3.12.4), can we also add a `.python-version` file that includes this?

Additionally, I had to run `pip install setuptools` that installs a missing dependency (according to this StackOverflow it was removed in Python 3.10, so we could use a lower version of Python 3 to avoid this step perhaps?)

We should probably add this step to the README just in case...

2024-10-25 00:10 UTC, andrewrubin submitted a review, later dismissed

2024-10-25 00:42 UTC, andrewrubin approved these changes, later dismissed

2024-10-25 16:23 UTC, andrewrubin approved these changes

2024-10-25 16:51 UTC, merged